plugins:
  discourse_classifieds_enabled:
    default: true
    client: true
  classifieds_add_to_top_menu:
    default: true
    client: true
  classifieds_add_to_hamburger_menu:
    default: true
    client: true
  classifieds_default_view:
    default: "grid"
    client: true
    type: enum
    choices:
      - "list"
      - "grid"
